VAR_SCALE = 'scale'
VAR_SCALE_DEFAULT = 1.0  # Full resolution by default
VAR_MONITOR = 'monitor'
VAR_MONITOR_DEFAULT = 0
VAR_SHOULD_UPDATE_COMMANDS = 'update_commands'
VAR_SHOULD_UPDATE_COMMANDS_DEFAULT = True
VAR_FPS = 'fps'
VAR_FPS_DEFAULT = 30  # Balanced FPS
VAR_JPEG_QUALITY = 'jpeg_quality'
VAR_JPEG_QUALITY_DEFAULT = 95  # Maximum quality by default
VAR_USE_NUMPY = 'use_numpy'
VAR_USE_NUMPY_DEFAULT = False  # JPEG is faster for most cases
VAR_COMPRESSION_LEVEL = 'compression_level'
VAR_COMPRESSION_LEVEL_DEFAULT = 3
VAR_USE_RAW_SOCKETS = 'use_raw_sockets'
VAR_USE_RAW_SOCKETS_DEFAULT = True

COMMAND_SET_VAR = 'set_var'
COMMAND_SEND_SCREENSHOT = 'send_screenshot'
COMMAND_NEW_COMMAND = 'command'
COMMAND_SCROLL = 'scroll'