VAR_SCALE = 'scale'
VAR_SCALE_DEFAULT = 1.0  # Full resolution by default
VAR_MONITOR = 'monitor'
VAR_MONITOR_DEFAULT = 0
VAR_SHOULD_UPDATE_COMMANDS = 'update_commands'
VAR_SHOULD_UPDATE_COMMANDS_DEFAULT = True
VAR_FPS = 'fps'
VAR_FPS_DEFAULT = 30  # Balanced FPS for high quality
VAR_JPEG_QUALITY = 'jpeg_quality'
VAR_JPEG_QUALITY_DEFAULT = 95  # High quality for better image fidelity
VAR_USE_NUMPY = 'use_numpy'
VAR_USE_NUMPY_DEFAULT = False  # JPEG is faster for most cases
VAR_COMPRESSION_LEVEL = 'compression_level'
VAR_COMPRESSION_LEVEL_DEFAULT = 6  # Higher compression for numpy
VAR_USE_DELTA = 'use_delta'
VAR_USE_DELTA_DEFAULT = True  # Use delta encoding for better FPS
VAR_USE_RAW_SOCKETS = 'use_raw_sockets'
VAR_USE_RAW_SOCKETS_DEFAULT = True

COMMAND_SET_VAR = 'set_var'
COMMAND_SEND_SCREENSHOT = 'send_screenshot'
COMMAND_NEW_COMMAND = 'command'
COMMAND_SCROLL = 'scroll'